-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.2
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/prettier/prettier.git
    sha: 1.6.1
    hooks:
    -   id: prettier
        files: ^\.(css|less|scss|html|ts|tsx|graphql|gql|json|js|jsx|.*rc)$
