-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.2
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: prettier
        name: prettier
        entry: yarn run format
        language: node
        pass_filenames: false
        always_run: true
