language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js: 'node'
sudo: required
before_install:
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
- yarn global add greenkeeper-lockfile@latest
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:
- yarn run coverage:upload
- yarn run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
