language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js: 'node'
before_install:
- npm install -g yarn@latest
- yarn global add greenkeeper-lockfile@latest
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:
- yarn run coverage:upload
- yarn run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
