language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: 'node'
before_install:
- npm install -g npm@latest
- npm install -g greenkeeper-lockfile@latest
before_script:
- npm prune
- greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:
- npm run coverage:upload
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
