var DESTINATION = {}
DESTINATION.FILE = 'destination'

var SOURCES = {}
SOURCES.DIRECTORY = '/sources/'
SOURCES.GLOB = SOURCES.DIRECTORY + '*'

var SOURCE = {}
SOURCE.FILE = SOURCES.DIRECTORY + 'source'
SOURCE.FILES = [
  SOURCES.DIRECTORY + 'a',
  SOURCES.DIRECTORY + 'b',
  SOURCES.DIRECTORY + 'c'
]

export { DESTINATION, SOURCES, SOURCE }
